const productMasterData = [
    {
      category: "Electronics",
      productName: "Washing Machine",
      sku: "452",
      description: "Washing Machine description here",
      price: 1500,
      discount: 10,
    },
    {
      category: "Electronics",
      productName: "Air Conditioner",
      sku: "455",
      description: "Air Conditioner description here",
      price: 3500,
      discount: 10,
    },
    {
      category: "Electronics",
      productName: "Refrigerator",
      sku: "459",
      description: "Refrigerator description here",
      price: 4000,
      discount: 10,
    },
    {
      category: "Cosmetics",
      productName: "Shaving Cream",
      sku: "659",
      description: "Shaving Cream description here",
      price: 40,
      discount: 7,
    },
    {
      category: "Cosmetics",
      productName: "Razor",
      sku: "658",
      description: "Razor description here",
      price: 45,
      discount: 10,
    },
    {
      category: "Clothing",
      productName: "Trouser",
      sku: "789",
      description: "Trouser description here",
      price: 26,
      discount: 5,
    },
    {
      category: "Clothing",
      productName: "Woven Shirt",
      sku: "1236",
      description: "Woven Shirt description here",
      price: 12,
      discount: 10,
    },
    {
      category: "Medicines",
      productName: "Aspirin 15mg",
      sku: "990",
      description: "Aspirin 15mg description here",
      price: 5.5,
      discount: 5,
    },
    {
      category: "Medicines",
      productName: "VCure 30 mg",
      sku: "991",
      description: "VCure 30 mg description here",
      price: 7.4,
      discount: 5,
    },
  ];
  export default productMasterData;